#!/bin/bash

# check if argument is not missing
if [ -z "$1" ]; then
	echo "Error: Missing whonix version. Please provide an whonix version."
	exit 1
fi

# set options
set -o nounset
set -e
set -x

# variables and configuration
NAME="whonix"
DM="derivative-maker"
DB="derivative-binary"
WB="whonix-binary"
VERSION="$1"
VERSION_NUMBER="${WHONIX_VERSION%%-*}"
REPOSITORY="https://github.com/Whonix/derivative-maker.git"
FLAVOR_GATEWAY="whonix-gateway-xfce"
FLAVOR_WORKSTATION="whonix-workstation-xfce"
TARGET="utm"
ARCH="arm64"
TB="open"
REPO="true"
SIZE_GATEWAY="15G"
SIZE_WORKSTATION="25G"

# Functions
function cleanup() {
  # clean up setup
  rm -rf "$HOME"/derivative-maker
  rm -rf "$HOME"/derivative-binary
  rm -rf "$HOME"/whonix-binary
  rm -rf "$HOME"/build-log
  touch "$HOME"/build-log
}

function update_install() {
  # updates/upgrades and autoremove packages
  echo "Starting $NAME build for version $VERSION" 
  sudo apt update -y
  sudo apt upgrade -y
  sudo apt autoremove -y
  # install dependencies
  local PACKAGES=("git" "time" "curl" "apt-cacher-ng" "lsb-release" "fakeroot" "fasttrack-archive-keyring")
  # Loop through each package
  for PACKAGE in "${PACKAGES[@]}"; do
      if ! dpkg -l "$PACKAGE" &> /dev/null; then
          echo "$PACKAGE is not installed. Installing..."
          sudo apt install -y "$PACKAGE" 2>&1 | tee -a ~/build-log
      else
          echo "$PACKAGE is already installed."
      fi
  done
}

function repo_down() {
  # download git repository
  echo "Git clone $NAME version $VERSION"
  git clone --depth=1 --branch "$VERSION" --jobs=4 --recurse-submodules --shallow-submodules $WHONIX_REPOSITORY
  cd "$HOME"/derivative-maker

  # verifies correct version is downloaded
  GIT_VERSION="$(git describe --tags --abbrev=0)"
  if [ "$GIT_VERSION" == "$VERSION" ]; then
    echo "Git version matches the desired version ($VERSION)."
  else
    echo "Git version does not match the desired version ($VERSION)."
    exit 2
  fi
}

function verify_tag() {
  # verifies git tag with gpg keyring
  cd "$HOME"/"$DM"

  # Verify if the current directory is a git repository
  if git rev-parse --git-dir > /dev/null 2>&1; then
    if git verify-tag "$WHONIX_VERSION"; then
      echo "Commit verification succeeded."
    else
      echo "Commit verification failed."
      # Handle the failure case, e.g., exit the script or perform some recovery actions
      exit 4
    fi
  else
    echo "Not a git repository. Please run this script within a git repository."
    exit 3
  fi
}


function build() {
  # build the project
  cd "$HOME"/"$DM"

  echo "Building gateway"
  "$HOME"/"$DM"/"$DM" --flavor "$FLAVOR_GATEWAY" --target "$TARGET" --arch "$ARCH" --tb "$TB" --repo "$REPO" --vmsize "$SIZE_GATEWAY"
  
  echo "Building workstation"
  "$HOME"/"$DM"/"$DM" --flavor "$FLAVOR_WORKSTATION" --target "$TARGET" --arch "$ARCH" --tb "$TB" --repo "$REPO" --vmsize "$SIZE_WORKSTATION"
}

function pack() {
  # cp binary tar.gz files into another directory for easy access
  mkdir "$HOME"/"$WB"
  cp -vr "$HOME"/"$DB"/"$VERSION_NUMBER"/*.utm.tar.gz "$HOME"/"$WB"
  echo "Build of $NAME version $WHONIX_VERSION is finished"
}

# starts scripts
echo "Starting $NAME build function"
cd "$HOME"
cleanup

# everything from here on will be included in build-log
update_install 2>&1 | tee -a ~/build-log
if [ ! -f "$HOME"/"$DM" ]; then
  repo_down 2>&1 | tee -a ~/build-log
fi
verify_tag 2>&1 | tee -a ~/build-log
build 2>&1 | tee -a ~/build-log
pack 2>&1 | tee -a ~/build-log

# cp build log to whonix folder and completing the script
cp "$HOME"/build-log "$HOME"/"$WB"/
echo "Build function finished, please check log"
cd "$HOME"
exit 0
